// <auto-generated />
using System;
using Api_Integrador.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api_Integrador.Migrations
{
    [DbContext(typeof(Api_IntegradorContext))]
    partial class Api_IntegradorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Modelos_Integrador.AccionAdministrativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AccionesAdministrativas");
                });

            modelBuilder.Entity("Modelos_Integrador.Administrador", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RolId");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("Modelos_Integrador.Confederacion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Confederaciones");
                });

            modelBuilder.Entity("Modelos_Integrador.Estadio", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SedeId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SedeId");

                    b.ToTable("Estadios");
                });

            modelBuilder.Entity("Modelos_Integrador.Grupo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("Modelos_Integrador.Partido", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("EstadioID")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("FaseDeJuego")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("GolesLocal")
                        .HasColumnType("int");

                    b.Property<int?>("GolesVisitante")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time(6)");

                    b.Property<int>("SeleccionLocalID")
                        .HasColumnType("int");

                    b.Property<int>("SeleccionVisitanteID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("EstadioID");

                    b.HasIndex("SeleccionLocalID");

                    b.HasIndex("SeleccionVisitanteID");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("Modelos_Integrador.RegistroAuditoria", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AccionAdministrativaId")
                        .HasColumnType("int");

                    b.Property<int>("AdministradorId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.HasIndex("AccionAdministrativaId");

                    b.HasIndex("AdministradorId");

                    b.ToTable("RegistroAuditorias");
                });

            modelBuilder.Entity("Modelos_Integrador.Rol", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Modelos_Integrador.Sede", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Sedes");
                });

            modelBuilder.Entity("Modelos_Integrador.Seleccion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CodigoFifa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ConfederacionId")
                        .HasColumnType("int");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("ConfederacionId");

                    b.HasIndex("GrupoId");

                    b.ToTable("selecciones");
                });

            modelBuilder.Entity("Modelos_Integrador.Administrador", b =>
                {
                    b.HasOne("Modelos_Integrador.Rol", "Rol")
                        .WithMany("administradores")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Modelos_Integrador.Estadio", b =>
                {
                    b.HasOne("Modelos_Integrador.Sede", "Sede")
                        .WithMany("Estadios")
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("Modelos_Integrador.Partido", b =>
                {
                    b.HasOne("Modelos_Integrador.Estadio", "Estadio")
                        .WithMany("Partidos")
                        .HasForeignKey("EstadioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelos_Integrador.Seleccion", "SeleccionLocal")
                        .WithMany("PartidosComoLocal")
                        .HasForeignKey("SeleccionLocalID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Modelos_Integrador.Seleccion", "SeleccionVisitante")
                        .WithMany("PartidosComoVisitante")
                        .HasForeignKey("SeleccionVisitanteID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estadio");

                    b.Navigation("SeleccionLocal");

                    b.Navigation("SeleccionVisitante");
                });

            modelBuilder.Entity("Modelos_Integrador.RegistroAuditoria", b =>
                {
                    b.HasOne("Modelos_Integrador.AccionAdministrativa", "AccionAdministrativa")
                        .WithMany("RegistrosAuditoria")
                        .HasForeignKey("AccionAdministrativaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelos_Integrador.Administrador", "Administrador")
                        .WithMany("RegistrosAuditoria")
                        .HasForeignKey("AdministradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccionAdministrativa");

                    b.Navigation("Administrador");
                });

            modelBuilder.Entity("Modelos_Integrador.Seleccion", b =>
                {
                    b.HasOne("Modelos_Integrador.Confederacion", "Confederacion")
                        .WithMany("Selecciones")
                        .HasForeignKey("ConfederacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelos_Integrador.Grupo", "Grupo")
                        .WithMany("Selecciones")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Confederacion");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("Modelos_Integrador.AccionAdministrativa", b =>
                {
                    b.Navigation("RegistrosAuditoria");
                });

            modelBuilder.Entity("Modelos_Integrador.Administrador", b =>
                {
                    b.Navigation("RegistrosAuditoria");
                });

            modelBuilder.Entity("Modelos_Integrador.Confederacion", b =>
                {
                    b.Navigation("Selecciones");
                });

            modelBuilder.Entity("Modelos_Integrador.Estadio", b =>
                {
                    b.Navigation("Partidos");
                });

            modelBuilder.Entity("Modelos_Integrador.Grupo", b =>
                {
                    b.Navigation("Selecciones");
                });

            modelBuilder.Entity("Modelos_Integrador.Rol", b =>
                {
                    b.Navigation("administradores");
                });

            modelBuilder.Entity("Modelos_Integrador.Sede", b =>
                {
                    b.Navigation("Estadios");
                });

            modelBuilder.Entity("Modelos_Integrador.Seleccion", b =>
                {
                    b.Navigation("PartidosComoLocal");

                    b.Navigation("PartidosComoVisitante");
                });
#pragma warning restore 612, 618
        }
    }
}
